# Generated by Django 5.0.1 on 2024-01-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_remove_hotel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='available_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
